<div class="main-slideshow">
			<div id="rev_slider_116_1_wrapper" class="rev_slider_wrapper fullwidthbanner-container" data-alias="layer-animations" style="margin:0px auto;background-color:transparent;padding:0px;margin-top:0px;margin-bottom:0px;">
				<!-- START REVOLUTION SLIDER 5.0.7 auto mode -->
				<div id="rev_slider_116_1" class="rev_slider fullwidthabanner" style="display:none;" data-version="5.0.7">
					<ul>
						<?php 
						$query_4 = "SELECT * FROM `sliders` WHERE `app_id` = '$app_id' ORDER BY display_order ASC";
						$result_4 = mysqli_query($link, $query_4);
						while($row_4 = mysqli_fetch_assoc($result_4))
						{
						?>	
						<li data-index="<?php echo $row_4['slider_name']; ?>" data-transition="parallaxhorizontal" data-slotamount="default" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="uploads/store-<?=$app_id; ?>/sliders/<?php echo $row_4['file_name']; ?>" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="1500" data-fsslotamount="7" data-saveperformance="off" data-title="<?php echo $row_4['slider_name']; ?>" data-description="">
							<!-- MAIN IMAGE -->
							<img src="uploads/store-<?=$app_id; ?>/sliders/<?php echo $row_4['file_name']; ?>" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
							<!-- LAYER NR. 1 -->
							<!--<i class="tp-caption layer1 tp-resizeme" id="slide3-layer1" data-x="100" data-hoffset="" data-y="250" data-voffset="-70" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;tO:0% 50%;" data-transform_in="x:-50px;rY:-90deg;opacity:0;s:2000;e:Back.easeOut;" data-transform_out="s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-start="2000" data-splitin="lines" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05" style="font-size:24px; letter-spacing:1px;  text-transform:uppercase; color:#666; font-style:normal;">Special offer sale up to 45% off</i>-->
							<!-- LAYER NR. 2 -->
							<!--<div class="tp-caption layer2 tp-resizeme" id="slide3-layer2" data-x="0" data-hoffset="" data-y="280" data-voffset="" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;tO:0% 50%;" data-transform_in="x:[-175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0.01;s:3000;e:Power3.easeOut;" data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;" data-mask_in="x:[100%];y:0;s:inherit;e:inherit;" data-start="2000" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05" style="font-size:55px;letter-spacing:1px; text-transform:uppercase; color:#1f1f1f; line-height:70px"><?php echo $row_4['slider_name']; ?></div>-->
							<!-- LAYER NR. 3 -->
							<!--<i class="tp-caption layer7 tp-resizeme" id="slide3-layer3" data-x="100" data-hoffset="" data-y="360" data-voffset="" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="3000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="font-size:20px; letter-spacing:1px;padding:5px 20px; font-style:normal; font-weight:600;  text-transform:uppercase;"></i>-->
							<!-- LAYER NR. 4 -->
							<!--<a href="#" class="tp-caption layer4 tp-resizeme rs-parallaxlevel-9" id="slide3-layer4" data-x="250" data-hoffset="" data-y="410" data-voffset="" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="3300" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="font-size:15px; font-weight:500; padding:10px 25px; text-transform:uppercase;">Special offer</a> </li>-->
						<?php
						}
						?>
						
						
						<!--<li data-index="Hot Summer" data-transition="parallaxhorizontal" data-slotamount="default" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="images/slider/t-slider-bg2.jpg" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="1500" data-fsslotamount="7" data-saveperformance="off" data-title="Electronics" data-description="">
							<img src="images/slider/slider-bg2.jpg" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
							<i class="tp-caption layer1 tp-resizeme" id="slide1-layer1" data-x="center" data-hoffset="" data-y="300" data-voffset="-150" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;" data-transform_in="x:[105%];z:0;rX:45deg;rY:0deg;rZ:90deg;sX:1;sY:1;skX:0;skY:0;s:2000;e:Power4.easeInOut;" data-transform_out="s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1000" data-splitin="chars" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05" style="font-size:24px; letter-spacing:1px; text-transform:uppercase; font-style:normal; color:#eee;">A Nice top title ShopLook</i>
							<div class="tp-caption layer2 tp-resizeme" id="slide1-layer2" data-x="center" data-hoffset="" data-y="330" data-voffset="" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;tO:0% 50%;" data-transform_in="x:[-175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0.01;s:3000;e:Power3.easeOut;" data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;" data-mask_in="x:[100%];y:0;s:inherit;e:inherit;" data-start="2000" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05" style="font-size:55px;letter-spacing:1px; text-transform:uppercase; line-height:70px">Hot Summer Fashion</div>
							<i class="tp-caption layer3 tp-resizeme" id="slide1-layer3" data-x="center" data-hoffset="" data-y="420" data-voffset="" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="3000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="font-size:20px; letter-spacing:1px;padding:5px 20px; text-transform:uppercase; font-style:normal; font-weight:500; color:#fff;">IS ON! Hurry Grab one Now!</i>
						
							<a href="#" class="tp-caption layer4 tp-resizeme rs-parallaxlevel-9" id="slide1-layer4" data-x="center" data-hoffset="" data-y="500" data-voffset="" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="3300" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="font-size:15px; font-weight:600; padding:10px 25px; text-transform:uppercase;">Shop Now</a> </li>
						<li data-index="New Trend" data-transition="parallaxhorizontal" data-slotamount="default" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="images/slider/t-slider-bg3.jpg" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="1500" data-fsslotamount="7" data-saveperformance="off" data-title="Furniture" data-description="">
							<img src="images/slider/slider-bg3.jpg" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
							<div class="tp-caption layer10 tp-resizeme rs-parallaxlevel-9" id="slide7-layer1" data-x="600" data-hoffset="" data-y="200" data-voffset="" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:90deg;rY:0;rZ:0;sX:3;sY:3;skX:0;skY:0;s:1500;e:Power3.easeInOut;" data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1000" data-splitin="chars" data-splitout="none" data-elementdelay="0.05" style="font-size:125px;color:#fff; line-height:135px; ">New Trend</div>
							<div class="tp-caption layer10 tp-resizeme rs-parallaxlevel-9" id="slide7-layer2" data-x="600" data-hoffset="" data-y="320" data-voffset="" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:90deg;rY:0;rZ:0;sX:3;sY:3;skX:0;skY:0;s:1500;e:Power3.easeInOut;" data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1500" data-splitin="chars" data-splitout="none" data-elementdelay="0.05" style="font-size:125px; color:#fff;line-height:135px; ">Big Style </div>
							<i class="tp-caption layer7 tp-resizeme" id="slide7-layer3" data-x="720" data-hoffset="" data-y="480" data-voffset="-70" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;" data-transform_in="x:[-105%];z:0;rX:0deg;rY:0deg;rZ:-90deg;sX:1;sY:1;skX:0;skY:0;s:2000;e:Power4.easeInOut;" data-transform_out="s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="2000" data-splitin="chars" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05" style="font-size:20px;color:#eee; letter-spacing:2px; font-size:18px; font-style:normal;">Furnish your Classic and Modern Designer</i>
							<a href="#" class="tp-caption layer4 tp-resizeme rs-parallaxlevel-9" id="slide7-layer4" data-x="850" data-hoffset="" data-y="550" data-voffset="" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="3300" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="font-size:15px; font-weight:600; padding:10px 25px; text-transform:uppercase;">Shop now</a> </li>
						<li data-index="Men" data-transition="parallaxhorizontal" data-slotamount="default" data-easein="default" data-easeout="default" data-masterspeed="default" data-thumb="images/slider/t-slider-bg4.jpg" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="1500" data-fsslotamount="7" data-saveperformance="off" data-title="Men" data-description="">
							<img src="images/slider/slider-bg4.jpg" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" class="rev-slidebg" data-no-retina>
							<a href="#" class="tp-caption layer8 tp-resizeme rs-parallaxlevel-9" id="slide6-layer1" data-x="0" data-hoffset="" data-y="250" data-voffset="" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="1000" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="font-size:35px;width: 100px;height: 100px;line-height: 100px; border-radius:100%;"><i class="fa fa-tags"></i> </a>
							<div class="tp-caption layer2 tp-resizeme" id="slide6-layer2" data-x="0" data-hoffset="" data-y="370" data-voffset="" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;" data-transform_in="x:{-50,50};y:{-5,50};rX:{-90,90};rY:{-90,90};rZ:{-360,360};sX:0;sY:0;opacity:0;s:2000;e:Power4.easeInOut;" data-transform_out="s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-start="3490" data-splitin="chars" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05" style="font-size:50px;letter-spacing:0; text-transform:uppercase;">Casual Collection For Men</div>
							<div class="tp-caption layer7 tp-resizeme" id="slide6-layer3" data-x="0" data-hoffset="" data-y="440" data-voffset="-70" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;" data-transform_in="x:[-105%];z:0;rX:0deg;rY:0deg;rZ:-90deg;sX:1;sY:1;skX:0;skY:0;s:2000;e:Power4.easeInOut;" data-transform_out="s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="2000" data-splitin="chars" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05" style="font-size:24px; letter-spacing:2px; text-transform:uppercase; color:#333;">New Fall Clothes for men</div>
							<a href="#" class="tp-caption layer9 tp-resizeme rs-parallaxlevel-9" id="slide6-layer4" data-x="0" data-hoffset="" data-y="500" data-voffset="" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="3300" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="font-size:15px; font-weight:600; padding:10px 25px; text-transform:uppercase;">Click Here</a>

							<a href="#" class="tp-caption layer4 tp-resizeme rs-parallaxlevel-9" id="slide6-layer5" data-x="160" data-hoffset="" data-y="500" data-voffset="" data-width="['auto','auto','auto','auto']" data-height="['auto','auto','auto','auto']" data-transform_idle="o:1;" data-transform_in="y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;s:1500;e:Power3.easeInOut;" data-transform_out="s:1000;e:Power3.easeInOut;s:1000;e:Power3.easeInOut;" data-mask_in="x:0px;y:0px;s:inherit;e:inherit;" data-start="3600" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="font-size:15px; font-weight:600; padding:10px 25px; text-transform:uppercase;">View Colletion</a> </li>-->
					</ul>
				</div>
			</div>
		</div>